# Development için
FROM node:20-alpine
WORKDIR /app

# package dosyaları
COPY package*.json ./
RUN npm ci

# kaynak kod
COPY . .

EXPOSE 3000

# Development server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
